version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /my-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /my-app/docker-credentials/password

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - pip install -r code/requirements.txt

  build:
    commands:
      - cd code
      - echo "Building Docker Image"
      - if [ -z "$DOCKER_REGISTRY_PASSWORD" ]; then echo "DOCKER_REGISTRY_PASSWORD is empty"; exit 1; fi
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin https://index.docker.io/v1/
      - docker build -t "$DOCKER_REGISTRY_USERNAME/test-pipeline-app:latest" .
      - docker push "$DOCKER_REGISTRY_USERNAME/test-pipeline-app:latest"

  post_build:
    commands:
      - echo "Build is successful"
