name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select action"
        required: true
        type: choice
        options:
          - plan
          - apply
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - tst
          - prd

permissions:
  id-token: write
  contents: read

jobs:
  deploy-tst:
    if: github.event.inputs.environment == 'tst'
    uses: ./.github/workflows/pipeline-tst.yml
    with:
      action: ${{ github.event.inputs.action }}

  deploy-prd:
    if: github.event.inputs.environment == 'prd'
    uses: ./.github/workflows/pipeline-prd.yml
    with:
      action: ${{ github.event.inputs.action }}