name: Azure Terraform TST

on:
  workflow_call:
    inputs:
      client_id:
        required: true
        type: string
      tenant_id:
        required: true
        type: string
      subscription_id:
        required: true
        type: string

jobs:
  Plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id:       ${{ inputs.client_id }}
          tenant-id:       ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  Apply:
    needs: Plan
    runs-on: ubuntu-latest
    environment: tst

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id:       ${{ inputs.client_id }}
          tenant-id:       ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan